config/routes.rb
Rails.application.routes.draw do
  root "homes#index"

  resources :blogs

  get '/blogs/test', to: "blogs#test"

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
    @blog = Blog.new
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    # respond_to do |format|
    #   format.json{
    #     if @blog.save
    #       render json: @blog
    #     else
    #       render nothing: true
    #     end
    #   }
    # end
    if @blog.save
      render :show_ajax, layout: false
    else
    end
  end

  def show
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path
  end

  private
    def blog_params
      params.require(:blog).permit(:title, :body)
    end

    def set_blog
      @blog = Blog.find(params[:id])
    end

    def authenticate_user!
      redirect_to "/" unless session[:user_id].present?
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    @time = Time.now
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/blogs/_form.html.erb
<%= form_for @blog do |f| %>
  <div>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.submit "Post" %>
  </div>

<% end %>

app/views/blogs/edit.html.erb
<h1>Edit Blog</h1>

<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>All Blogs</h1>

<%= render 'form' %>



<ul id="blog-list">
  <% @blogs.each do |blog| %>
<!--     <li>
      <a href='<%= "/blogs/#{blog.id}" %>'>
        <%= blog.title %>
      </a>
    </li> -->
    <li><%= link_to blog.title, blog %></li>
  <% end %>
</ul>


<script>

  $(document).ready(function(){
    $("#new_blog").submit(function(e){
      e.preventDefault();
      var action = $(this).attr('action');
      var method = $(this).attr('method');
      var formData = $(this).serialize();

      $.ajax({
        type: method,
        url: action,
        data: formData
        // dataType: "json"
      }).done(function(response){
        // $("#blog-list").append('<li><a href="/blogs/'+ response.id +'">' + response.title + '</a></li>')
        $("#blog-list").append(response)
      })
    })

  })

</script>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

app/views/blogs/show.html.erb
<h3><%= @blog.title %></h3>

<p>
  <%= @blog.body %>
</p>

<%= link_to "Edit Blog", edit_blog_path(@blog)  %>

<%= link_to "Delete Blog", blog_path(@blog), method: :delete  %>
<!-- 
<form action="/blogs/:id" method="POST">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="delete">
</form> -->

app/views/blogs/show_ajax.html.erb
<li>
  <%= link_to @blog.title, @blog %>
</li>

app/views/homes/index.html.erb
<h3>The time is now <%= @time %></h3>


<a href="/blogs/new">New Blog</a>
<%= link_to "New Blog", "/blogs/new" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeerBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>